language: python
addons:
  apt:
    packages:
    - ncbi-blast+
python:
  - "2.7"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo -E apt-get install -qq ncbi-blast+"
# command to run tests
script: nosetests --with-coverage --cover-package=chromosomer
after_success:
  - coveralls

